apiVersion: v1
kind: Service
metadata:
  name: snatchlock-service
spec:
  type: NodePort
  selector:
    app: snatchlock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # This must match the containerPort above
      nodePort: 30080   # You can access the app on this port from the host
